=begin
CurateND Query API

Prototype of the CurateND Query API. This is a work in progress. 

OpenAPI spec version: 0.0.0
Contact: curate@nd.edu
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/api/v0/objects/{id}/content', controller_name: 'binaryFiles', action_name: 'objects_id_content_get'
  add_swagger_route 'HEAD', '/api/v0/objects/{id}/content', controller_name: 'binaryFiles', action_name: 'objects_id_content_head'
  add_swagger_route 'GET', '/api/v0/objects/{id}/thumbnail', controller_name: 'binaryFiles', action_name: 'objects_id_thumbnail_get'
  add_swagger_route 'HEAD', '/api/v0/objects/{id}/thumbnail', controller_name: 'binaryFiles', action_name: 'objects_id_thumbnail_head'
  add_swagger_route 'GET', '/api/v0/objects/{id}', controller_name: 'default', action_name: 'objects_id_get'
  add_swagger_route 'GET', '/api/v0/search', controller_name: 'default', action_name: 'search_get'
end
